/*
 * Copyright (C) 2007-2012 Siemens AG
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/*******************************************************************
 *
 * @author Daniel.Peintner.EXT@siemens.com
 * @version 0.6 
 * @contact Joerg.Heuer@siemens.com
 *
 * <p>Code generated by EXIdizer</p>
 ********************************************************************/



#include "EncoderChannel.h"
#include "CoderChannel.h"
#include "BitOutputStream.h"
#include "EXITypes.h"
#include "MethodsBag.h"

#ifndef BYTE_ENCODER_CHANNEL_C
#define BYTE_ENCODER_CHANNEL_C

#if EXI_ALIGNMENT == BYTE_ALIGNMENT


int encode(bitstream_t* stream, uint8_t b) {
#if EXI_STREAM == BYTE_ARRAY
	if ( (*stream->pos) < stream->size ) {
		stream->data[(*stream->pos)++] = b;
		return 0;
	} else {
		return EXI_ERROR_OUTPUT_STREAM_EOF;
	}
#endif /* EXI_STREAM == BYTE_ARRAY */
#if EXI_STREAM == FILE_STREAM
	if ( putc(b, stream->file) == EOF ) {
		return EXI_ERROR_OUTPUT_STREAM_EOF;
	} else {
		return 0;
	}
#endif /* EXI_STREAM == FILE_STREAM */
}

/**
 * Encode a single boolean value. A false value is encoded as byte 0 and true
 * value is encode as byte 1.
 */
int encodeBoolean(bitstream_t* stream, int b) {
	uint8_t val = b ? 1 : 0;
	return encode(stream, val);
}


/**
 * Encode n-bit unsigned integer. The n least significant bits of parameter
 * b starting with the most significant, i.e. from left to right.
 */
int encodeNBitUnsignedInteger(bitstream_t* stream, uint16_t nbits, uint32_t val)  {
	if (nbits > 0) {
		if (nbits < 9) {
			/* 1 byte */
			encode(stream, val & 0xff);
		} else if (nbits < 17) {
			/* 2 bytes */
			encode(stream, val & 0x00ff);
			encode(stream, (val & 0xff00) >> 8);
		} else if (nbits < 25) {
			/* 3 bytes */
			encode(stream, val & 0x0000ff);
			encode(stream, (val & 0x00ff00) >> 8);
			encode(stream, (val & 0xff0000) >> 16);
		} else if (nbits < 33) {
			/* 4 bytes */
			encode(stream, val & 0x000000ff);
			encode(stream, (val & 0x0000ff00) >> 8);
			encode(stream, (val & 0x00ff0000) >> 16);
			encode(stream, (val & 0xff000000) >> 24);
		} else {
			/* TODO Currently not more than 4 Bytes allowed for NBitUnsignedInteger */
			return EXI_UNSUPPORTED_NBIT_INTEGER_LENGTH;
		}
	}
	return 0;
}


/**
 * Flush underlying bit output stream.
 */
int encodeFinish(bitstream_t* stream) {
	/* no pending bits in byte-aligned mode */
	return 0;
}

#endif /* alignment */

#endif












