/*
 * Copyright (C) 2007-2012 Siemens AG
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/*******************************************************************
 *
 * @author Daniel.Peintner.EXT@siemens.com
 * @version 0.6
 * @contact Joerg.Heuer@siemens.com
 *
 * <p>Code generated by EXIdizer</p>
 ********************************************************************/



#ifdef __cplusplus
extern "C" {
#endif

#ifndef EXI_appHand_ENCODER_H
#define EXI_appHand_ENCODER_H

#include "EXITypes.h"

int exiappHandInitEncoder(bitstream_t* stream, exi_state_t* state,
		exi_name_table_runtime_t runtimeTable);

int exiappHandEncodeStartDocument(bitstream_t* stream,
		exi_state_t* state);

int exiappHandEncodeEndDocument(bitstream_t* stream,
		exi_state_t* state);

int
exiappHandEncodeStartElement(bitstream_t* stream,
		exi_state_t* state, eqname_t* se);

int exiappHandEncodeStartElementGeneric(bitstream_t* stream,
		exi_state_t* state, string_ascii_t* namespaceURI,
		string_ascii_t* localName);

int exiappHandEncodeEndElement(bitstream_t* stream,
		exi_state_t* state);

int exiappHandEncodeCharacters(bitstream_t* stream,
		exi_state_t* state, exi_value_t* val);

int exiappHandEncodeAttribute(bitstream_t* stream,
		exi_state_t* state, eqname_t* at, exi_value_t* val);

int exiappHandEncodeAttributeXsiNil(bitstream_t* stream,
		exi_state_t* state, exi_value_t* val);

int exiappHandEncodeAttributeXsiType(bitstream_t* stream,
		exi_state_t* state, exi_value_t* val);

#endif

#ifdef __cplusplus
}
#endif

