/*
 * Copyright (C) 2007-2012 Siemens AG
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/*******************************************************************
 *
 * @author Daniel.Peintner.EXT@siemens.com
 * @version 0.7
 * @contact Joerg.Heuer@siemens.com
 *
 * <p>Code generated by EXIdizer.com</p>
 ********************************************************************/



#ifndef EXI__QNAMES_C
#define EXI__QNAMES_C

#include "EXITypes.h"
#include "ErrorCodes.h"
#include "QNameDefines.h"

/* qname is a composition of namespaceURI(ID) and localPart(ID) */
static exi_eqname_t qnames[EXI_MAX_NUMBER_OF_QNAMES] = {
	/* qnameID == 0: Algorithm */
	{0, 0},
	/* qnameID == 1: Encoding */
	{0, 1},
	/* qnameID == 2: Id */
	{0, 2},
	/* qnameID == 3: MimeType */
	{0, 3},
	/* qnameID == 4: Name */
	{0, 4},
	/* qnameID == 5: Target */
	{0, 5},
	/* qnameID == 6: Type */
	{0, 6},
	/* qnameID == 7: URI */
	{0, 7},
	/* qnameID == 8: ValueType */
	{0, 8},
	/* qnameID == 9: {http://www.w3.org/XML/1998/namespace}base */
	{1, 0},
	/* qnameID == 10: {http://www.w3.org/XML/1998/namespace}id */
	{1, 1},
	/* qnameID == 11: {http://www.w3.org/XML/1998/namespace}lang */
	{1, 2},
	/* qnameID == 12: {http://www.w3.org/XML/1998/namespace}space */
	{1, 3},
	/* qnameID == 13: {http://www.w3.org/2001/XMLSchema-instance}nil */
	{2, 0},
	/* qnameID == 14: {http://www.w3.org/2001/XMLSchema-instance}type */
	{2, 1},
	/* qnameID == 15: {http://www.w3.org/2001/XMLSchema}ENTITIES */
	{3, 0},
	/* qnameID == 16: {http://www.w3.org/2001/XMLSchema}ENTITY */
	{3, 1},
	/* qnameID == 17: {http://www.w3.org/2001/XMLSchema}ID */
	{3, 2},
	/* qnameID == 18: {http://www.w3.org/2001/XMLSchema}IDREF */
	{3, 3},
	/* qnameID == 19: {http://www.w3.org/2001/XMLSchema}IDREFS */
	{3, 4},
	/* qnameID == 20: {http://www.w3.org/2001/XMLSchema}NCName */
	{3, 5},
	/* qnameID == 21: {http://www.w3.org/2001/XMLSchema}NMTOKEN */
	{3, 6},
	/* qnameID == 22: {http://www.w3.org/2001/XMLSchema}NMTOKENS */
	{3, 7},
	/* qnameID == 23: {http://www.w3.org/2001/XMLSchema}NOTATION */
	{3, 8},
	/* qnameID == 24: {http://www.w3.org/2001/XMLSchema}Name */
	{3, 9},
	/* qnameID == 25: {http://www.w3.org/2001/XMLSchema}QName */
	{3, 10},
	/* qnameID == 26: {http://www.w3.org/2001/XMLSchema}anySimpleType */
	{3, 11},
	/* qnameID == 27: {http://www.w3.org/2001/XMLSchema}anyType */
	{3, 12},
	/* qnameID == 28: {http://www.w3.org/2001/XMLSchema}anyURI */
	{3, 13},
	/* qnameID == 29: {http://www.w3.org/2001/XMLSchema}base64Binary */
	{3, 14},
	/* qnameID == 30: {http://www.w3.org/2001/XMLSchema}boolean */
	{3, 15},
	/* qnameID == 31: {http://www.w3.org/2001/XMLSchema}byte */
	{3, 16},
	/* qnameID == 32: {http://www.w3.org/2001/XMLSchema}date */
	{3, 17},
	/* qnameID == 33: {http://www.w3.org/2001/XMLSchema}dateTime */
	{3, 18},
	/* qnameID == 34: {http://www.w3.org/2001/XMLSchema}decimal */
	{3, 19},
	/* qnameID == 35: {http://www.w3.org/2001/XMLSchema}double */
	{3, 20},
	/* qnameID == 36: {http://www.w3.org/2001/XMLSchema}duration */
	{3, 21},
	/* qnameID == 37: {http://www.w3.org/2001/XMLSchema}float */
	{3, 22},
	/* qnameID == 38: {http://www.w3.org/2001/XMLSchema}gDay */
	{3, 23},
	/* qnameID == 39: {http://www.w3.org/2001/XMLSchema}gMonth */
	{3, 24},
	/* qnameID == 40: {http://www.w3.org/2001/XMLSchema}gMonthDay */
	{3, 25},
	/* qnameID == 41: {http://www.w3.org/2001/XMLSchema}gYear */
	{3, 26},
	/* qnameID == 42: {http://www.w3.org/2001/XMLSchema}gYearMonth */
	{3, 27},
	/* qnameID == 43: {http://www.w3.org/2001/XMLSchema}hexBinary */
	{3, 28},
	/* qnameID == 44: {http://www.w3.org/2001/XMLSchema}int */
	{3, 29},
	/* qnameID == 45: {http://www.w3.org/2001/XMLSchema}integer */
	{3, 30},
	/* qnameID == 46: {http://www.w3.org/2001/XMLSchema}language */
	{3, 31},
	/* qnameID == 47: {http://www.w3.org/2001/XMLSchema}long */
	{3, 32},
	/* qnameID == 48: {http://www.w3.org/2001/XMLSchema}negativeInteger */
	{3, 33},
	/* qnameID == 49: {http://www.w3.org/2001/XMLSchema}nonNegativeInteger */
	{3, 34},
	/* qnameID == 50: {http://www.w3.org/2001/XMLSchema}nonPositiveInteger */
	{3, 35},
	/* qnameID == 51: {http://www.w3.org/2001/XMLSchema}normalizedString */
	{3, 36},
	/* qnameID == 52: {http://www.w3.org/2001/XMLSchema}positiveInteger */
	{3, 37},
	/* qnameID == 53: {http://www.w3.org/2001/XMLSchema}short */
	{3, 38},
	/* qnameID == 54: {http://www.w3.org/2001/XMLSchema}string */
	{3, 39},
	/* qnameID == 55: {http://www.w3.org/2001/XMLSchema}time */
	{3, 40},
	/* qnameID == 56: {http://www.w3.org/2001/XMLSchema}token */
	{3, 41},
	/* qnameID == 57: {http://www.w3.org/2001/XMLSchema}unsignedByte */
	{3, 42},
	/* qnameID == 58: {http://www.w3.org/2001/XMLSchema}unsignedInt */
	{3, 43},
	/* qnameID == 59: {http://www.w3.org/2001/XMLSchema}unsignedLong */
	{3, 44},
	/* qnameID == 60: {http://www.w3.org/2001/XMLSchema}unsignedShort */
	{3, 45},
	/* qnameID == 61: {http://www.w3.org/2000/09/xmldsig#}CanonicalizationMethod */
	{4, 0},
	/* qnameID == 62: {http://www.w3.org/2000/09/xmldsig#}CanonicalizationMethodType */
	{4, 1},
	/* qnameID == 63: {http://www.w3.org/2000/09/xmldsig#}CryptoBinary */
	{4, 2},
	/* qnameID == 64: {http://www.w3.org/2000/09/xmldsig#}DSAKeyValue */
	{4, 3},
	/* qnameID == 65: {http://www.w3.org/2000/09/xmldsig#}DSAKeyValueType */
	{4, 4},
	/* qnameID == 66: {http://www.w3.org/2000/09/xmldsig#}DigestMethod */
	{4, 5},
	/* qnameID == 67: {http://www.w3.org/2000/09/xmldsig#}DigestMethodType */
	{4, 6},
	/* qnameID == 68: {http://www.w3.org/2000/09/xmldsig#}DigestValue */
	{4, 7},
	/* qnameID == 69: {http://www.w3.org/2000/09/xmldsig#}DigestValueType */
	{4, 8},
	/* qnameID == 70: {http://www.w3.org/2000/09/xmldsig#}Exponent */
	{4, 9},
	/* qnameID == 71: {http://www.w3.org/2000/09/xmldsig#}G */
	{4, 10},
	/* qnameID == 72: {http://www.w3.org/2000/09/xmldsig#}HMACOutputLength */
	{4, 11},
	/* qnameID == 73: {http://www.w3.org/2000/09/xmldsig#}HMACOutputLengthType */
	{4, 12},
	/* qnameID == 74: {http://www.w3.org/2000/09/xmldsig#}J */
	{4, 13},
	/* qnameID == 75: {http://www.w3.org/2000/09/xmldsig#}KeyInfo */
	{4, 14},
	/* qnameID == 76: {http://www.w3.org/2000/09/xmldsig#}KeyInfoType */
	{4, 15},
	/* qnameID == 77: {http://www.w3.org/2000/09/xmldsig#}KeyName */
	{4, 16},
	/* qnameID == 78: {http://www.w3.org/2000/09/xmldsig#}KeyValue */
	{4, 17},
	/* qnameID == 79: {http://www.w3.org/2000/09/xmldsig#}KeyValueType */
	{4, 18},
	/* qnameID == 80: {http://www.w3.org/2000/09/xmldsig#}Manifest */
	{4, 19},
	/* qnameID == 81: {http://www.w3.org/2000/09/xmldsig#}ManifestType */
	{4, 20},
	/* qnameID == 82: {http://www.w3.org/2000/09/xmldsig#}MgmtData */
	{4, 21},
	/* qnameID == 83: {http://www.w3.org/2000/09/xmldsig#}Modulus */
	{4, 22},
	/* qnameID == 84: {http://www.w3.org/2000/09/xmldsig#}Object */
	{4, 23},
	/* qnameID == 85: {http://www.w3.org/2000/09/xmldsig#}ObjectType */
	{4, 24},
	/* qnameID == 86: {http://www.w3.org/2000/09/xmldsig#}P */
	{4, 25},
	/* qnameID == 87: {http://www.w3.org/2000/09/xmldsig#}PGPData */
	{4, 26},
	/* qnameID == 88: {http://www.w3.org/2000/09/xmldsig#}PGPDataType */
	{4, 27},
	/* qnameID == 89: {http://www.w3.org/2000/09/xmldsig#}PGPKeyID */
	{4, 28},
	/* qnameID == 90: {http://www.w3.org/2000/09/xmldsig#}PGPKeyPacket */
	{4, 29},
	/* qnameID == 91: {http://www.w3.org/2000/09/xmldsig#}PgenCounter */
	{4, 30},
	/* qnameID == 92: {http://www.w3.org/2000/09/xmldsig#}Q */
	{4, 31},
	/* qnameID == 93: {http://www.w3.org/2000/09/xmldsig#}RSAKeyValue */
	{4, 32},
	/* qnameID == 94: {http://www.w3.org/2000/09/xmldsig#}RSAKeyValueType */
	{4, 33},
	/* qnameID == 95: {http://www.w3.org/2000/09/xmldsig#}Reference */
	{4, 34},
	/* qnameID == 96: {http://www.w3.org/2000/09/xmldsig#}ReferenceType */
	{4, 35},
	/* qnameID == 97: {http://www.w3.org/2000/09/xmldsig#}RetrievalMethod */
	{4, 36},
	/* qnameID == 98: {http://www.w3.org/2000/09/xmldsig#}RetrievalMethodType */
	{4, 37},
	/* qnameID == 99: {http://www.w3.org/2000/09/xmldsig#}SPKIData */
	{4, 38},
	/* qnameID == 100: {http://www.w3.org/2000/09/xmldsig#}SPKIDataType */
	{4, 39},
	/* qnameID == 101: {http://www.w3.org/2000/09/xmldsig#}SPKISexp */
	{4, 40},
	/* qnameID == 102: {http://www.w3.org/2000/09/xmldsig#}Seed */
	{4, 41},
	/* qnameID == 103: {http://www.w3.org/2000/09/xmldsig#}Signature */
	{4, 42},
	/* qnameID == 104: {http://www.w3.org/2000/09/xmldsig#}SignatureMethod */
	{4, 43},
	/* qnameID == 105: {http://www.w3.org/2000/09/xmldsig#}SignatureMethodType */
	{4, 44},
	/* qnameID == 106: {http://www.w3.org/2000/09/xmldsig#}SignatureProperties */
	{4, 45},
	/* qnameID == 107: {http://www.w3.org/2000/09/xmldsig#}SignaturePropertiesType */
	{4, 46},
	/* qnameID == 108: {http://www.w3.org/2000/09/xmldsig#}SignatureProperty */
	{4, 47},
	/* qnameID == 109: {http://www.w3.org/2000/09/xmldsig#}SignaturePropertyType */
	{4, 48},
	/* qnameID == 110: {http://www.w3.org/2000/09/xmldsig#}SignatureType */
	{4, 49},
	/* qnameID == 111: {http://www.w3.org/2000/09/xmldsig#}SignatureValue */
	{4, 50},
	/* qnameID == 112: {http://www.w3.org/2000/09/xmldsig#}SignatureValueType */
	{4, 51},
	/* qnameID == 113: {http://www.w3.org/2000/09/xmldsig#}SignedInfo */
	{4, 52},
	/* qnameID == 114: {http://www.w3.org/2000/09/xmldsig#}SignedInfoType */
	{4, 53},
	/* qnameID == 115: {http://www.w3.org/2000/09/xmldsig#}Transform */
	{4, 54},
	/* qnameID == 116: {http://www.w3.org/2000/09/xmldsig#}TransformType */
	{4, 55},
	/* qnameID == 117: {http://www.w3.org/2000/09/xmldsig#}Transforms */
	{4, 56},
	/* qnameID == 118: {http://www.w3.org/2000/09/xmldsig#}TransformsType */
	{4, 57},
	/* qnameID == 119: {http://www.w3.org/2000/09/xmldsig#}X509CRL */
	{4, 58},
	/* qnameID == 120: {http://www.w3.org/2000/09/xmldsig#}X509Certificate */
	{4, 59},
	/* qnameID == 121: {http://www.w3.org/2000/09/xmldsig#}X509Data */
	{4, 60},
	/* qnameID == 122: {http://www.w3.org/2000/09/xmldsig#}X509DataType */
	{4, 61},
	/* qnameID == 123: {http://www.w3.org/2000/09/xmldsig#}X509IssuerName */
	{4, 62},
	/* qnameID == 124: {http://www.w3.org/2000/09/xmldsig#}X509IssuerSerial */
	{4, 63},
	/* qnameID == 125: {http://www.w3.org/2000/09/xmldsig#}X509IssuerSerialType */
	{4, 64},
	/* qnameID == 126: {http://www.w3.org/2000/09/xmldsig#}X509SKI */
	{4, 65},
	/* qnameID == 127: {http://www.w3.org/2000/09/xmldsig#}X509SerialNumber */
	{4, 66},
	/* qnameID == 128: {http://www.w3.org/2000/09/xmldsig#}X509SubjectName */
	{4, 67},
	/* qnameID == 129: {http://www.w3.org/2000/09/xmldsig#}XPath */
	{4, 68},
	/* qnameID == 130: {http://www.w3.org/2000/09/xmldsig#}Y */
	{4, 69},
	/* qnameID == 131: {urn:iso:15118:2:2010:MsgBody}AC_EVSEStatus */
	{5, 0},
	/* qnameID == 132: {urn:iso:15118:2:2010:MsgBody}BulkChargingComplete */
	{5, 1},
	/* qnameID == 133: {urn:iso:15118:2:2010:MsgBody}CableCheckReq */
	{5, 2},
	/* qnameID == 134: {urn:iso:15118:2:2010:MsgBody}CableCheckReqType */
	{5, 3},
	/* qnameID == 135: {urn:iso:15118:2:2010:MsgBody}CableCheckRes */
	{5, 4},
	/* qnameID == 136: {urn:iso:15118:2:2010:MsgBody}CableCheckResType */
	{5, 5},
	/* qnameID == 137: {urn:iso:15118:2:2010:MsgBody}CertificateInstallationReq */
	{5, 6},
	/* qnameID == 138: {urn:iso:15118:2:2010:MsgBody}CertificateInstallationReqType */
	{5, 7},
	/* qnameID == 139: {urn:iso:15118:2:2010:MsgBody}CertificateInstallationRes */
	{5, 8},
	/* qnameID == 140: {urn:iso:15118:2:2010:MsgBody}CertificateInstallationResType */
	{5, 9},
	/* qnameID == 141: {urn:iso:15118:2:2010:MsgBody}CertificateUpdateReq */
	{5, 10},
	/* qnameID == 142: {urn:iso:15118:2:2010:MsgBody}CertificateUpdateReqType */
	{5, 11},
	/* qnameID == 143: {urn:iso:15118:2:2010:MsgBody}CertificateUpdateRes */
	{5, 12},
	/* qnameID == 144: {urn:iso:15118:2:2010:MsgBody}CertificateUpdateResType */
	{5, 13},
	/* qnameID == 145: {urn:iso:15118:2:2010:MsgBody}ChargeParameterDiscoveryReq */
	{5, 14},
	/* qnameID == 146: {urn:iso:15118:2:2010:MsgBody}ChargeParameterDiscoveryReqType */
	{5, 15},
	/* qnameID == 147: {urn:iso:15118:2:2010:MsgBody}ChargeParameterDiscoveryRes */
	{5, 16},
	/* qnameID == 148: {urn:iso:15118:2:2010:MsgBody}ChargeParameterDiscoveryResType */
	{5, 17},
	/* qnameID == 149: {urn:iso:15118:2:2010:MsgBody}ChargeService */
	{5, 18},
	/* qnameID == 150: {urn:iso:15118:2:2010:MsgBody}ChargingComplete */
	{5, 19},
	/* qnameID == 151: {urn:iso:15118:2:2010:MsgBody}ChargingProfile */
	{5, 20},
	/* qnameID == 152: {urn:iso:15118:2:2010:MsgBody}ChargingStatusReq */
	{5, 21},
	/* qnameID == 153: {urn:iso:15118:2:2010:MsgBody}ChargingStatusReqType */
	{5, 22},
	/* qnameID == 154: {urn:iso:15118:2:2010:MsgBody}ChargingStatusRes */
	{5, 23},
	/* qnameID == 155: {urn:iso:15118:2:2010:MsgBody}ChargingStatusResType */
	{5, 24},
	/* qnameID == 156: {urn:iso:15118:2:2010:MsgBody}ContractAuthenticationReq */
	{5, 25},
	/* qnameID == 157: {urn:iso:15118:2:2010:MsgBody}ContractAuthenticationReqType */
	{5, 26},
	/* qnameID == 158: {urn:iso:15118:2:2010:MsgBody}ContractAuthenticationRes */
	{5, 27},
	/* qnameID == 159: {urn:iso:15118:2:2010:MsgBody}ContractAuthenticationResType */
	{5, 28},
	/* qnameID == 160: {urn:iso:15118:2:2010:MsgBody}ContractID */
	{5, 29},
	/* qnameID == 161: {urn:iso:15118:2:2010:MsgBody}ContractSignatureCertChain */
	{5, 30},
	/* qnameID == 162: {urn:iso:15118:2:2010:MsgBody}ContractSignatureEncryptedPrivateKey */
	{5, 31},
	/* qnameID == 163: {urn:iso:15118:2:2010:MsgBody}CurrentDemandReq */
	{5, 32},
	/* qnameID == 164: {urn:iso:15118:2:2010:MsgBody}CurrentDemandReqType */
	{5, 33},
	/* qnameID == 165: {urn:iso:15118:2:2010:MsgBody}CurrentDemandRes */
	{5, 34},
	/* qnameID == 166: {urn:iso:15118:2:2010:MsgBody}CurrentDemandResType */
	{5, 35},
	/* qnameID == 167: {urn:iso:15118:2:2010:MsgBody}DC_EVSEStatus */
	{5, 36},
	/* qnameID == 168: {urn:iso:15118:2:2010:MsgBody}DC_EVStatus */
	{5, 37},
	/* qnameID == 169: {urn:iso:15118:2:2010:MsgBody}DHParams */
	{5, 38},
	/* qnameID == 170: {urn:iso:15118:2:2010:MsgBody}DateTimeNow */
	{5, 39},
	/* qnameID == 171: {urn:iso:15118:2:2010:MsgBody}EVCCID */
	{5, 40},
	/* qnameID == 172: {urn:iso:15118:2:2010:MsgBody}EVMaximumCurrentLimit */
	{5, 41},
	/* qnameID == 173: {urn:iso:15118:2:2010:MsgBody}EVMaximumPowerLimit */
	{5, 42},
	/* qnameID == 174: {urn:iso:15118:2:2010:MsgBody}EVMaximumVoltageLimit */
	{5, 43},
	/* qnameID == 175: {urn:iso:15118:2:2010:MsgBody}EVRequestedEnergyTransferType */
	{5, 44},
	/* qnameID == 176: {urn:iso:15118:2:2010:MsgBody}EVSECurrentLimitAchieved */
	{5, 45},
	/* qnameID == 177: {urn:iso:15118:2:2010:MsgBody}EVSEID */
	{5, 46},
	/* qnameID == 178: {urn:iso:15118:2:2010:MsgBody}EVSEMaxCurrent */
	{5, 47},
	/* qnameID == 179: {urn:iso:15118:2:2010:MsgBody}EVSEMaximumCurrentLimit */
	{5, 48},
	/* qnameID == 180: {urn:iso:15118:2:2010:MsgBody}EVSEMaximumPowerLimit */
	{5, 49},
	/* qnameID == 181: {urn:iso:15118:2:2010:MsgBody}EVSEMaximumVoltageLimit */
	{5, 50},
	/* qnameID == 182: {urn:iso:15118:2:2010:MsgBody}EVSEPowerLimitAchieved */
	{5, 51},
	/* qnameID == 183: {urn:iso:15118:2:2010:MsgBody}EVSEPresentCurrent */
	{5, 52},
	/* qnameID == 184: {urn:iso:15118:2:2010:MsgBody}EVSEPresentVoltage */
	{5, 53},
	/* qnameID == 185: {urn:iso:15118:2:2010:MsgBody}EVSEProcessing */
	{5, 54},
	/* qnameID == 186: {urn:iso:15118:2:2010:MsgBody}EVSEVoltageLimitAchieved */
	{5, 55},
	/* qnameID == 187: {urn:iso:15118:2:2010:MsgBody}EVTargetCurrent */
	{5, 56},
	/* qnameID == 188: {urn:iso:15118:2:2010:MsgBody}EVTargetVoltage */
	{5, 57},
	/* qnameID == 189: {urn:iso:15118:2:2010:MsgBody}GenChallenge */
	{5, 58},
	/* qnameID == 190: {urn:iso:15118:2:2010:MsgBody}ListOfRootCertificateIDs */
	{5, 59},
	/* qnameID == 191: {urn:iso:15118:2:2010:MsgBody}MeterInfo */
	{5, 60},
	/* qnameID == 192: {urn:iso:15118:2:2010:MsgBody}MeteringReceiptReq */
	{5, 61},
	/* qnameID == 193: {urn:iso:15118:2:2010:MsgBody}MeteringReceiptReqType */
	{5, 62},
	/* qnameID == 194: {urn:iso:15118:2:2010:MsgBody}MeteringReceiptRes */
	{5, 63},
	/* qnameID == 195: {urn:iso:15118:2:2010:MsgBody}MeteringReceiptResType */
	{5, 64},
	/* qnameID == 196: {urn:iso:15118:2:2010:MsgBody}OEMProvisioningCert */
	{5, 65},
	/* qnameID == 197: {urn:iso:15118:2:2010:MsgBody}PaymentDetailsReq */
	{5, 66},
	/* qnameID == 198: {urn:iso:15118:2:2010:MsgBody}PaymentDetailsReqType */
	{5, 67},
	/* qnameID == 199: {urn:iso:15118:2:2010:MsgBody}PaymentDetailsRes */
	{5, 68},
	/* qnameID == 200: {urn:iso:15118:2:2010:MsgBody}PaymentDetailsResType */
	{5, 69},
	/* qnameID == 201: {urn:iso:15118:2:2010:MsgBody}PaymentOptions */
	{5, 70},
	/* qnameID == 202: {urn:iso:15118:2:2010:MsgBody}PowerDeliveryReq */
	{5, 71},
	/* qnameID == 203: {urn:iso:15118:2:2010:MsgBody}PowerDeliveryReqType */
	{5, 72},
	/* qnameID == 204: {urn:iso:15118:2:2010:MsgBody}PowerDeliveryRes */
	{5, 73},
	/* qnameID == 205: {urn:iso:15118:2:2010:MsgBody}PowerDeliveryResType */
	{5, 74},
	/* qnameID == 206: {urn:iso:15118:2:2010:MsgBody}PreChargeReq */
	{5, 75},
	/* qnameID == 207: {urn:iso:15118:2:2010:MsgBody}PreChargeReqType */
	{5, 76},
	/* qnameID == 208: {urn:iso:15118:2:2010:MsgBody}PreChargeRes */
	{5, 77},
	/* qnameID == 209: {urn:iso:15118:2:2010:MsgBody}PreChargeResType */
	{5, 78},
	/* qnameID == 210: {urn:iso:15118:2:2010:MsgBody}ReadyToChargeState */
	{5, 79},
	/* qnameID == 211: {urn:iso:15118:2:2010:MsgBody}ReceiptRequired */
	{5, 80},
	/* qnameID == 212: {urn:iso:15118:2:2010:MsgBody}RemainingTimeToBulkSoC */
	{5, 81},
	/* qnameID == 213: {urn:iso:15118:2:2010:MsgBody}RemainingTimeToFullSoC */
	{5, 82},
	/* qnameID == 214: {urn:iso:15118:2:2010:MsgBody}ResponseCode */
	{5, 83},
	/* qnameID == 215: {urn:iso:15118:2:2010:MsgBody}RetryCounter */
	{5, 84},
	/* qnameID == 216: {urn:iso:15118:2:2010:MsgBody}SAScheduleTupleID */
	{5, 85},
	/* qnameID == 217: {urn:iso:15118:2:2010:MsgBody}SelectedPaymentOption */
	{5, 86},
	/* qnameID == 218: {urn:iso:15118:2:2010:MsgBody}SelectedServiceList */
	{5, 87},
	/* qnameID == 219: {urn:iso:15118:2:2010:MsgBody}ServiceCategory */
	{5, 88},
	/* qnameID == 220: {urn:iso:15118:2:2010:MsgBody}ServiceDetailReq */
	{5, 89},
	/* qnameID == 221: {urn:iso:15118:2:2010:MsgBody}ServiceDetailReqType */
	{5, 90},
	/* qnameID == 222: {urn:iso:15118:2:2010:MsgBody}ServiceDetailRes */
	{5, 91},
	/* qnameID == 223: {urn:iso:15118:2:2010:MsgBody}ServiceDetailResType */
	{5, 92},
	/* qnameID == 224: {urn:iso:15118:2:2010:MsgBody}ServiceDiscoveryReq */
	{5, 93},
	/* qnameID == 225: {urn:iso:15118:2:2010:MsgBody}ServiceDiscoveryReqType */
	{5, 94},
	/* qnameID == 226: {urn:iso:15118:2:2010:MsgBody}ServiceDiscoveryRes */
	{5, 95},
	/* qnameID == 227: {urn:iso:15118:2:2010:MsgBody}ServiceDiscoveryResType */
	{5, 96},
	/* qnameID == 228: {urn:iso:15118:2:2010:MsgBody}ServiceID */
	{5, 97},
	/* qnameID == 229: {urn:iso:15118:2:2010:MsgBody}ServiceList */
	{5, 98},
	/* qnameID == 230: {urn:iso:15118:2:2010:MsgBody}ServiceParameterList */
	{5, 99},
	/* qnameID == 231: {urn:iso:15118:2:2010:MsgBody}ServicePaymentSelectionReq */
	{5, 100},
	/* qnameID == 232: {urn:iso:15118:2:2010:MsgBody}ServicePaymentSelectionReqType */
	{5, 101},
	/* qnameID == 233: {urn:iso:15118:2:2010:MsgBody}ServicePaymentSelectionRes */
	{5, 102},
	/* qnameID == 234: {urn:iso:15118:2:2010:MsgBody}ServicePaymentSelectionResType */
	{5, 103},
	/* qnameID == 235: {urn:iso:15118:2:2010:MsgBody}ServiceScope */
	{5, 104},
	/* qnameID == 236: {urn:iso:15118:2:2010:MsgBody}SessionID */
	{5, 105},
	/* qnameID == 237: {urn:iso:15118:2:2010:MsgBody}SessionSetupReq */
	{5, 106},
	/* qnameID == 238: {urn:iso:15118:2:2010:MsgBody}SessionSetupReqType */
	{5, 107},
	/* qnameID == 239: {urn:iso:15118:2:2010:MsgBody}SessionSetupRes */
	{5, 108},
	/* qnameID == 240: {urn:iso:15118:2:2010:MsgBody}SessionSetupResType */
	{5, 109},
	/* qnameID == 241: {urn:iso:15118:2:2010:MsgBody}SessionStopReq */
	{5, 110},
	/* qnameID == 242: {urn:iso:15118:2:2010:MsgBody}SessionStopRes */
	{5, 111},
	/* qnameID == 243: {urn:iso:15118:2:2010:MsgBody}SessionStopResType */
	{5, 112},
	/* qnameID == 244: {urn:iso:15118:2:2010:MsgBody}SessionStopType */
	{5, 113},
	/* qnameID == 245: {urn:iso:15118:2:2010:MsgBody}WeldingDetectionReq */
	{5, 114},
	/* qnameID == 246: {urn:iso:15118:2:2010:MsgBody}WeldingDetectionReqType */
	{5, 115},
	/* qnameID == 247: {urn:iso:15118:2:2010:MsgBody}WeldingDetectionRes */
	{5, 116},
	/* qnameID == 248: {urn:iso:15118:2:2010:MsgBody}WeldingDetectionResType */
	{5, 117},
	/* qnameID == 249: {urn:iso:15118:2:2010:MsgDataTypes}AC_EVChargeParameter */
	{6, 0},
	/* qnameID == 250: {urn:iso:15118:2:2010:MsgDataTypes}AC_EVChargeParameterType */
	{6, 1},
	/* qnameID == 251: {urn:iso:15118:2:2010:MsgDataTypes}AC_EVSEChargeParameter */
	{6, 2},
	/* qnameID == 252: {urn:iso:15118:2:2010:MsgDataTypes}AC_EVSEChargeParameterType */
	{6, 3},
	/* qnameID == 253: {urn:iso:15118:2:2010:MsgDataTypes}AC_EVSEStatus */
	{6, 4},
	/* qnameID == 254: {urn:iso:15118:2:2010:MsgDataTypes}AC_EVSEStatusType */
	{6, 5},
	/* qnameID == 255: {urn:iso:15118:2:2010:MsgDataTypes}BulkChargingComplete */
	{6, 6},
	/* qnameID == 256: {urn:iso:15118:2:2010:MsgDataTypes}BulkSOC */
	{6, 7},
	/* qnameID == 257: {urn:iso:15118:2:2010:MsgDataTypes}Certificate */
	{6, 8},
	/* qnameID == 258: {urn:iso:15118:2:2010:MsgDataTypes}CertificateChainType */
	{6, 9},
	/* qnameID == 259: {urn:iso:15118:2:2010:MsgDataTypes}ChargingComplete */
	{6, 10},
	/* qnameID == 260: {urn:iso:15118:2:2010:MsgDataTypes}ChargingProfileEntryMaxPower */
	{6, 11},
	/* qnameID == 261: {urn:iso:15118:2:2010:MsgDataTypes}ChargingProfileEntryStart */
	{6, 12},
	/* qnameID == 262: {urn:iso:15118:2:2010:MsgDataTypes}ChargingProfileType */
	{6, 13},
	/* qnameID == 263: {urn:iso:15118:2:2010:MsgDataTypes}ConsumptionCost */
	{6, 14},
	/* qnameID == 264: {urn:iso:15118:2:2010:MsgDataTypes}ConsumptionCostType */
	{6, 15},
	/* qnameID == 265: {urn:iso:15118:2:2010:MsgDataTypes}Cost */
	{6, 16},
	/* qnameID == 266: {urn:iso:15118:2:2010:MsgDataTypes}CostType */
	{6, 17},
	/* qnameID == 267: {urn:iso:15118:2:2010:MsgDataTypes}DC_EVChargeParameter */
	{6, 18},
	/* qnameID == 268: {urn:iso:15118:2:2010:MsgDataTypes}DC_EVChargeParameterType */
	{6, 19},
	/* qnameID == 269: {urn:iso:15118:2:2010:MsgDataTypes}DC_EVErrorCodeType */
	{6, 20},
	/* qnameID == 270: {urn:iso:15118:2:2010:MsgDataTypes}DC_EVPowerDeliveryParameter */
	{6, 21},
	/* qnameID == 271: {urn:iso:15118:2:2010:MsgDataTypes}DC_EVPowerDeliveryParameterType */
	{6, 22},
	/* qnameID == 272: {urn:iso:15118:2:2010:MsgDataTypes}DC_EVSEChargeParameter */
	{6, 23},
	/* qnameID == 273: {urn:iso:15118:2:2010:MsgDataTypes}DC_EVSEChargeParameterType */
	{6, 24},
	/* qnameID == 274: {urn:iso:15118:2:2010:MsgDataTypes}DC_EVSEStatus */
	{6, 25},
	/* qnameID == 275: {urn:iso:15118:2:2010:MsgDataTypes}DC_EVSEStatusCodeType */
	{6, 26},
	/* qnameID == 276: {urn:iso:15118:2:2010:MsgDataTypes}DC_EVSEStatusType */
	{6, 27},
	/* qnameID == 277: {urn:iso:15118:2:2010:MsgDataTypes}DC_EVStatus */
	{6, 28},
	/* qnameID == 278: {urn:iso:15118:2:2010:MsgDataTypes}DC_EVStatusType */
	{6, 29},
	/* qnameID == 279: {urn:iso:15118:2:2010:MsgDataTypes}DepartureTime */
	{6, 30},
	/* qnameID == 280: {urn:iso:15118:2:2010:MsgDataTypes}EAmount */
	{6, 31},
	/* qnameID == 281: {urn:iso:15118:2:2010:MsgDataTypes}EPriceLevel */
	{6, 32},
	/* qnameID == 282: {urn:iso:15118:2:2010:MsgDataTypes}EVCabinConditioning */
	{6, 33},
	/* qnameID == 283: {urn:iso:15118:2:2010:MsgDataTypes}EVChargeParameter */
	{6, 34},
	/* qnameID == 284: {urn:iso:15118:2:2010:MsgDataTypes}EVChargeParameterType */
	{6, 35},
	/* qnameID == 285: {urn:iso:15118:2:2010:MsgDataTypes}EVEnergyCapacity */
	{6, 36},
	/* qnameID == 286: {urn:iso:15118:2:2010:MsgDataTypes}EVEnergyRequest */
	{6, 37},
	/* qnameID == 287: {urn:iso:15118:2:2010:MsgDataTypes}EVErrorCode */
	{6, 38},
	/* qnameID == 288: {urn:iso:15118:2:2010:MsgDataTypes}EVMaxCurrent */
	{6, 39},
	/* qnameID == 289: {urn:iso:15118:2:2010:MsgDataTypes}EVMaxVoltage */
	{6, 40},
	/* qnameID == 290: {urn:iso:15118:2:2010:MsgDataTypes}EVMaximumCurrentLimit */
	{6, 41},
	/* qnameID == 291: {urn:iso:15118:2:2010:MsgDataTypes}EVMaximumPowerLimit */
	{6, 42},
	/* qnameID == 292: {urn:iso:15118:2:2010:MsgDataTypes}EVMaximumVoltageLimit */
	{6, 43},
	/* qnameID == 293: {urn:iso:15118:2:2010:MsgDataTypes}EVMinCurrent */
	{6, 44},
	/* qnameID == 294: {urn:iso:15118:2:2010:MsgDataTypes}EVPowerDeliveryParameter */
	{6, 45},
	/* qnameID == 295: {urn:iso:15118:2:2010:MsgDataTypes}EVPowerDeliveryParameterType */
	{6, 46},
	/* qnameID == 296: {urn:iso:15118:2:2010:MsgDataTypes}EVRESSConditioning */
	{6, 47},
	/* qnameID == 297: {urn:iso:15118:2:2010:MsgDataTypes}EVRESSSOC */
	{6, 48},
	/* qnameID == 298: {urn:iso:15118:2:2010:MsgDataTypes}EVReady */
	{6, 49},
	/* qnameID == 299: {urn:iso:15118:2:2010:MsgDataTypes}EVRequestedEnergyTransferType */
	{6, 50},
	/* qnameID == 300: {urn:iso:15118:2:2010:MsgDataTypes}EVSEChargeParameter */
	{6, 51},
	/* qnameID == 301: {urn:iso:15118:2:2010:MsgDataTypes}EVSEChargeParameterType */
	{6, 52},
	/* qnameID == 302: {urn:iso:15118:2:2010:MsgDataTypes}EVSECurrentRegulationTolerance */
	{6, 53},
	/* qnameID == 303: {urn:iso:15118:2:2010:MsgDataTypes}EVSEEnergyToBeDelivered */
	{6, 54},
	/* qnameID == 304: {urn:iso:15118:2:2010:MsgDataTypes}EVSEIsolationStatus */
	{6, 55},
	/* qnameID == 305: {urn:iso:15118:2:2010:MsgDataTypes}EVSEMaxCurrent */
	{6, 56},
	/* qnameID == 306: {urn:iso:15118:2:2010:MsgDataTypes}EVSEMaxVoltage */
	{6, 57},
	/* qnameID == 307: {urn:iso:15118:2:2010:MsgDataTypes}EVSEMaximumCurrentLimit */
	{6, 58},
	/* qnameID == 308: {urn:iso:15118:2:2010:MsgDataTypes}EVSEMaximumPowerLimit */
	{6, 59},
	/* qnameID == 309: {urn:iso:15118:2:2010:MsgDataTypes}EVSEMaximumVoltageLimit */
	{6, 60},
	/* qnameID == 310: {urn:iso:15118:2:2010:MsgDataTypes}EVSEMinCurrent */
	{6, 61},
	/* qnameID == 311: {urn:iso:15118:2:2010:MsgDataTypes}EVSEMinimumCurrentLimit */
	{6, 62},
	/* qnameID == 312: {urn:iso:15118:2:2010:MsgDataTypes}EVSEMinimumVoltageLimit */
	{6, 63},
	/* qnameID == 313: {urn:iso:15118:2:2010:MsgDataTypes}EVSENotification */
	{6, 64},
	/* qnameID == 314: {urn:iso:15118:2:2010:MsgDataTypes}EVSENotificationType */
	{6, 65},
	/* qnameID == 315: {urn:iso:15118:2:2010:MsgDataTypes}EVSEPeakCurrentRipple */
	{6, 66},
	/* qnameID == 316: {urn:iso:15118:2:2010:MsgDataTypes}EVSEProcessingType */
	{6, 67},
	/* qnameID == 317: {urn:iso:15118:2:2010:MsgDataTypes}EVSEStatus */
	{6, 68},
	/* qnameID == 318: {urn:iso:15118:2:2010:MsgDataTypes}EVSEStatusCode */
	{6, 69},
	/* qnameID == 319: {urn:iso:15118:2:2010:MsgDataTypes}EVSEStatusType */
	{6, 70},
	/* qnameID == 320: {urn:iso:15118:2:2010:MsgDataTypes}EVSESupportedEnergyTransferType */
	{6, 71},
	/* qnameID == 321: {urn:iso:15118:2:2010:MsgDataTypes}EVStatus */
	{6, 72},
	/* qnameID == 322: {urn:iso:15118:2:2010:MsgDataTypes}EVStatusType */
	{6, 73},
	/* qnameID == 323: {urn:iso:15118:2:2010:MsgDataTypes}EnergyTransferType */
	{6, 74},
	/* qnameID == 324: {urn:iso:15118:2:2010:MsgDataTypes}Entry */
	{6, 75},
	/* qnameID == 325: {urn:iso:15118:2:2010:MsgDataTypes}EntryType */
	{6, 76},
	/* qnameID == 326: {urn:iso:15118:2:2010:MsgDataTypes}FaultCode */
	{6, 77},
	/* qnameID == 327: {urn:iso:15118:2:2010:MsgDataTypes}FaultMsg */
	{6, 78},
	/* qnameID == 328: {urn:iso:15118:2:2010:MsgDataTypes}FreeService */
	{6, 79},
	/* qnameID == 329: {urn:iso:15118:2:2010:MsgDataTypes}FullSOC */
	{6, 80},
	/* qnameID == 330: {urn:iso:15118:2:2010:MsgDataTypes}IntervalType */
	{6, 81},
	/* qnameID == 331: {urn:iso:15118:2:2010:MsgDataTypes}ListOfRootCertificateIDsType */
	{6, 82},
	/* qnameID == 332: {urn:iso:15118:2:2010:MsgDataTypes}MeterID */
	{6, 83},
	/* qnameID == 333: {urn:iso:15118:2:2010:MsgDataTypes}MeterInfoType */
	{6, 84},
	/* qnameID == 334: {urn:iso:15118:2:2010:MsgDataTypes}MeterReading */
	{6, 85},
	/* qnameID == 335: {urn:iso:15118:2:2010:MsgDataTypes}MeterStatus */
	{6, 86},
	/* qnameID == 336: {urn:iso:15118:2:2010:MsgDataTypes}Multiplier */
	{6, 87},
	/* qnameID == 337: {urn:iso:15118:2:2010:MsgDataTypes}NotificationMaxDelay */
	{6, 88},
	/* qnameID == 338: {urn:iso:15118:2:2010:MsgDataTypes}NotificationType */
	{6, 89},
	/* qnameID == 339: {urn:iso:15118:2:2010:MsgDataTypes}NumEPriceLevels */
	{6, 90},
	/* qnameID == 340: {urn:iso:15118:2:2010:MsgDataTypes}PMax */
	{6, 91},
	/* qnameID == 341: {urn:iso:15118:2:2010:MsgDataTypes}PMaxSchedule */
	{6, 92},
	/* qnameID == 342: {urn:iso:15118:2:2010:MsgDataTypes}PMaxScheduleEntry */
	{6, 93},
	/* qnameID == 343: {urn:iso:15118:2:2010:MsgDataTypes}PMaxScheduleEntryType */
	{6, 94},
	/* qnameID == 344: {urn:iso:15118:2:2010:MsgDataTypes}PMaxScheduleID */
	{6, 95},
	/* qnameID == 345: {urn:iso:15118:2:2010:MsgDataTypes}PMaxScheduleType */
	{6, 96},
	/* qnameID == 346: {urn:iso:15118:2:2010:MsgDataTypes}PMaxType */
	{6, 97},
	/* qnameID == 347: {urn:iso:15118:2:2010:MsgDataTypes}Parameter */
	{6, 98},
	/* qnameID == 348: {urn:iso:15118:2:2010:MsgDataTypes}ParameterSet */
	{6, 99},
	/* qnameID == 349: {urn:iso:15118:2:2010:MsgDataTypes}ParameterSetID */
	{6, 100},
	/* qnameID == 350: {urn:iso:15118:2:2010:MsgDataTypes}ParameterSetType */
	{6, 101},
	/* qnameID == 351: {urn:iso:15118:2:2010:MsgDataTypes}ParameterType */
	{6, 102},
	/* qnameID == 352: {urn:iso:15118:2:2010:MsgDataTypes}PaymentOption */
	{6, 103},
	/* qnameID == 353: {urn:iso:15118:2:2010:MsgDataTypes}PaymentOptionsType */
	{6, 104},
	/* qnameID == 354: {urn:iso:15118:2:2010:MsgDataTypes}PhysicalValueType */
	{6, 105},
	/* qnameID == 355: {urn:iso:15118:2:2010:MsgDataTypes}PowerSwitchClosed */
	{6, 106},
	/* qnameID == 356: {urn:iso:15118:2:2010:MsgDataTypes}ProfileEntry */
	{6, 107},
	/* qnameID == 357: {urn:iso:15118:2:2010:MsgDataTypes}ProfileEntryType */
	{6, 108},
	/* qnameID == 358: {urn:iso:15118:2:2010:MsgDataTypes}RCD */
	{6, 109},
	/* qnameID == 359: {urn:iso:15118:2:2010:MsgDataTypes}RelativeTimeInterval */
	{6, 110},
	/* qnameID == 360: {urn:iso:15118:2:2010:MsgDataTypes}RelativeTimeIntervalType */
	{6, 111},
	/* qnameID == 361: {urn:iso:15118:2:2010:MsgDataTypes}RootCertificateID */
	{6, 112},
	/* qnameID == 362: {urn:iso:15118:2:2010:MsgDataTypes}SAIDType */
	{6, 113},
	/* qnameID == 363: {urn:iso:15118:2:2010:MsgDataTypes}SAScheduleList */
	{6, 114},
	/* qnameID == 364: {urn:iso:15118:2:2010:MsgDataTypes}SAScheduleListType */
	{6, 115},
	/* qnameID == 365: {urn:iso:15118:2:2010:MsgDataTypes}SAScheduleTuple */
	{6, 116},
	/* qnameID == 366: {urn:iso:15118:2:2010:MsgDataTypes}SAScheduleTupleID */
	{6, 117},
	/* qnameID == 367: {urn:iso:15118:2:2010:MsgDataTypes}SAScheduleTupleType */
	{6, 118},
	/* qnameID == 368: {urn:iso:15118:2:2010:MsgDataTypes}SASchedules */
	{6, 119},
	/* qnameID == 369: {urn:iso:15118:2:2010:MsgDataTypes}SASchedulesType */
	{6, 120},
	/* qnameID == 370: {urn:iso:15118:2:2010:MsgDataTypes}SalesTariff */
	{6, 121},
	/* qnameID == 371: {urn:iso:15118:2:2010:MsgDataTypes}SalesTariffDescription */
	{6, 122},
	/* qnameID == 372: {urn:iso:15118:2:2010:MsgDataTypes}SalesTariffEntry */
	{6, 123},
	/* qnameID == 373: {urn:iso:15118:2:2010:MsgDataTypes}SalesTariffEntryType */
	{6, 124},
	/* qnameID == 374: {urn:iso:15118:2:2010:MsgDataTypes}SalesTariffID */
	{6, 125},
	/* qnameID == 375: {urn:iso:15118:2:2010:MsgDataTypes}SalesTariffType */
	{6, 126},
	/* qnameID == 376: {urn:iso:15118:2:2010:MsgDataTypes}SelectedService */
	{6, 127},
	/* qnameID == 377: {urn:iso:15118:2:2010:MsgDataTypes}SelectedServiceListType */
	{6, 128},
	/* qnameID == 378: {urn:iso:15118:2:2010:MsgDataTypes}SelectedServiceType */
	{6, 129},
	/* qnameID == 379: {urn:iso:15118:2:2010:MsgDataTypes}Service */
	{6, 130},
	/* qnameID == 380: {urn:iso:15118:2:2010:MsgDataTypes}ServiceCategory */
	{6, 131},
	/* qnameID == 381: {urn:iso:15118:2:2010:MsgDataTypes}ServiceCharge */
	{6, 132},
	/* qnameID == 382: {urn:iso:15118:2:2010:MsgDataTypes}ServiceChargeType */
	{6, 133},
	/* qnameID == 383: {urn:iso:15118:2:2010:MsgDataTypes}ServiceID */
	{6, 134},
	/* qnameID == 384: {urn:iso:15118:2:2010:MsgDataTypes}ServiceName */
	{6, 135},
	/* qnameID == 385: {urn:iso:15118:2:2010:MsgDataTypes}ServiceParameterListType */
	{6, 136},
	/* qnameID == 386: {urn:iso:15118:2:2010:MsgDataTypes}ServiceScope */
	{6, 137},
	/* qnameID == 387: {urn:iso:15118:2:2010:MsgDataTypes}ServiceTag */
	{6, 138},
	/* qnameID == 388: {urn:iso:15118:2:2010:MsgDataTypes}ServiceTagListType */
	{6, 139},
	/* qnameID == 389: {urn:iso:15118:2:2010:MsgDataTypes}ServiceTagType */
	{6, 140},
	/* qnameID == 390: {urn:iso:15118:2:2010:MsgDataTypes}ServiceType */
	{6, 141},
	/* qnameID == 391: {urn:iso:15118:2:2010:MsgDataTypes}SigMeterReading */
	{6, 142},
	/* qnameID == 392: {urn:iso:15118:2:2010:MsgDataTypes}SubCertificates */
	{6, 143},
	/* qnameID == 393: {urn:iso:15118:2:2010:MsgDataTypes}SubCertificatesType */
	{6, 144},
	/* qnameID == 394: {urn:iso:15118:2:2010:MsgDataTypes}TMeter */
	{6, 145},
	/* qnameID == 395: {urn:iso:15118:2:2010:MsgDataTypes}TimeInterval */
	{6, 146},
	/* qnameID == 396: {urn:iso:15118:2:2010:MsgDataTypes}Unit */
	{6, 147},
	/* qnameID == 397: {urn:iso:15118:2:2010:MsgDataTypes}Value */
	{6, 148},
	/* qnameID == 398: {urn:iso:15118:2:2010:MsgDataTypes}amount */
	{6, 149},
	/* qnameID == 399: {urn:iso:15118:2:2010:MsgDataTypes}amountMultiplier */
	{6, 150},
	/* qnameID == 400: {urn:iso:15118:2:2010:MsgDataTypes}boolValue */
	{6, 151},
	/* qnameID == 401: {urn:iso:15118:2:2010:MsgDataTypes}byteValue */
	{6, 152},
	/* qnameID == 402: {urn:iso:15118:2:2010:MsgDataTypes}certificateType */
	{6, 153},
	/* qnameID == 403: {urn:iso:15118:2:2010:MsgDataTypes}contractIDType */
	{6, 154},
	/* qnameID == 404: {urn:iso:15118:2:2010:MsgDataTypes}costKind */
	{6, 155},
	/* qnameID == 405: {urn:iso:15118:2:2010:MsgDataTypes}costKindType */
	{6, 156},
	/* qnameID == 406: {urn:iso:15118:2:2010:MsgDataTypes}dHParamsType */
	{6, 157},
	/* qnameID == 407: {urn:iso:15118:2:2010:MsgDataTypes}duration */
	{6, 158},
	/* qnameID == 408: {urn:iso:15118:2:2010:MsgDataTypes}evccIDType */
	{6, 159},
	/* qnameID == 409: {urn:iso:15118:2:2010:MsgDataTypes}evseIDType */
	{6, 160},
	/* qnameID == 410: {urn:iso:15118:2:2010:MsgDataTypes}faultCodeType */
	{6, 161},
	/* qnameID == 411: {urn:iso:15118:2:2010:MsgDataTypes}faultMsgType */
	{6, 162},
	/* qnameID == 412: {urn:iso:15118:2:2010:MsgDataTypes}genChallengeType */
	{6, 163},
	/* qnameID == 413: {urn:iso:15118:2:2010:MsgDataTypes}intValue */
	{6, 164},
	/* qnameID == 414: {urn:iso:15118:2:2010:MsgDataTypes}isolationLevelType */
	{6, 165},
	/* qnameID == 415: {urn:iso:15118:2:2010:MsgDataTypes}meterIDType */
	{6, 166},
	/* qnameID == 416: {urn:iso:15118:2:2010:MsgDataTypes}meterStatusType */
	{6, 167},
	/* qnameID == 417: {urn:iso:15118:2:2010:MsgDataTypes}paymentOptionType */
	{6, 168},
	/* qnameID == 418: {urn:iso:15118:2:2010:MsgDataTypes}percentValueType */
	{6, 169},
	/* qnameID == 419: {urn:iso:15118:2:2010:MsgDataTypes}physicalValue */
	{6, 170},
	/* qnameID == 420: {urn:iso:15118:2:2010:MsgDataTypes}privateKeyType */
	{6, 171},
	/* qnameID == 421: {urn:iso:15118:2:2010:MsgDataTypes}responseCodeType */
	{6, 172},
	/* qnameID == 422: {urn:iso:15118:2:2010:MsgDataTypes}rootCertificateIDType */
	{6, 173},
	/* qnameID == 423: {urn:iso:15118:2:2010:MsgDataTypes}serviceCategoryType */
	{6, 174},
	/* qnameID == 424: {urn:iso:15118:2:2010:MsgDataTypes}serviceIDType */
	{6, 175},
	/* qnameID == 425: {urn:iso:15118:2:2010:MsgDataTypes}serviceNameType */
	{6, 176},
	/* qnameID == 426: {urn:iso:15118:2:2010:MsgDataTypes}serviceScopeType */
	{6, 177},
	/* qnameID == 427: {urn:iso:15118:2:2010:MsgDataTypes}sessionIDType */
	{6, 178},
	/* qnameID == 428: {urn:iso:15118:2:2010:MsgDataTypes}shortValue */
	{6, 179},
	/* qnameID == 429: {urn:iso:15118:2:2010:MsgDataTypes}sigMeterReadingType */
	{6, 180},
	/* qnameID == 430: {urn:iso:15118:2:2010:MsgDataTypes}start */
	{6, 181},
	/* qnameID == 431: {urn:iso:15118:2:2010:MsgDataTypes}startValue */
	{6, 182},
	/* qnameID == 432: {urn:iso:15118:2:2010:MsgDataTypes}stringValue */
	{6, 183},
	/* qnameID == 433: {urn:iso:15118:2:2010:MsgDataTypes}tariffDescriptionType */
	{6, 184},
	/* qnameID == 434: {urn:iso:15118:2:2010:MsgDataTypes}unitMultiplierType */
	{6, 185},
	/* qnameID == 435: {urn:iso:15118:2:2010:MsgDataTypes}unitSymbolType */
	{6, 186},
	/* qnameID == 436: {urn:iso:15118:2:2010:MsgDataTypes}valueType */
	{6, 187},
	/* qnameID == 437: {urn:iso:15118:2:2010:MsgDef}Body */
	{7, 0},
	/* qnameID == 438: {urn:iso:15118:2:2010:MsgDef}BodyBaseType */
	{7, 1},
	/* qnameID == 439: {urn:iso:15118:2:2010:MsgDef}BodyElement */
	{7, 2},
	/* qnameID == 440: {urn:iso:15118:2:2010:MsgDef}BodyType */
	{7, 3},
	/* qnameID == 441: {urn:iso:15118:2:2010:MsgDef}Header */
	{7, 4},
	/* qnameID == 442: {urn:iso:15118:2:2010:MsgDef}V2G_Message */
	{7, 5},
	/* qnameID == 443: {urn:iso:15118:2:2010:MsgHeader}MessageHeaderType */
	{8, 0},
	/* qnameID == 444: {urn:iso:15118:2:2010:MsgHeader}Notification */
	{8, 1},
	/* qnameID == 445: {urn:iso:15118:2:2010:MsgHeader}SessionID */
	{8, 2}

};


int exiGetEQName(exi_state_t* state, uint16_t qnameID, uint16_t* namespaceURI, uint16_t* localPart) {
	int errn = 0;
	/* EXI_NUMBER_OF_QNAMES */
	if (qnameID < state->nextQNameID) {
		*namespaceURI = qnames[qnameID].namespaceURI;
		*localPart = qnames[qnameID].localPart;
	} else {
		errn = EXI_ERROR_OUT_OF_BOUNDS;
	}
	return errn;
}


int exiGetQNameID(exi_state_t* state, uint16_t namespaceURI, uint16_t localPart, uint16_t* qnameID) {
	uint16_t i;
	/* TODO Do something more efficient than just walk over the entire list */
	/* EXI_NUMBER_OF_QNAMES */
	for(i=0; i<state->nextQNameID; i++) {
		if(qnames[i].localPart == localPart && qnames[i].namespaceURI == namespaceURI) {
			*qnameID = i;
			return 0;
		}
	}

	return EXI_ERROR_OUT_OF_BOUNDS;
}


int exiAddEQName(exi_state_t* state, uint16_t* qnameID, uint16_t namespaceURI, uint16_t localPart) {
	int errn = 0;
	if(state->nextQNameID < (EXI_MAX_NUMBER_OF_QNAMES -1)) {
		/* store IDs */
		qnames[state->nextQNameID].namespaceURI = namespaceURI;
		qnames[state->nextQNameID].localPart = localPart;
		/* increment counter */
		*qnameID = state->nextQNameID++;
	} else {
		errn = EXI_ERROR_OUT_OF_BOUNDS;
	}


	return errn;
}


#endif

